import type { Metadata } from "next";
import { Inter, JetBrains_Mono as FontMono } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Header from "@/components/headers/app-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" id="mode" className="light">
      <body className={GeistSans.className}>
        <Header>{children}</Header>
      </body>
    </html>
  );
}
